In [2]:
#function
def f(N):
    out = 1
    for i in xrange(N):
        out *= i+1
        
    return out

N= 10
print f(7)



5040


In [4]:
# tuple
t = (1,2,3,4,5,'ww',[1,2,3],(1,2),{'W1':2})
print t
print t[-1], len(t)

(1, 2, 3, 4, 5, 'ww', [1, 2, 3], (1, 2), {'W1': 2})
{'W1': 2} 9


In [6]:
# list
l = [1,2,3,'deep learning',[1,2,3],(1,2,3),{'person': 'xu'}]
a = l[3]
print a
print l

deep learning
[1, 2, 3, 'deep learning', [1, 2, 3], (1, 2, 3), {'person': 'xu'}]


In [9]:
# dictionary
d = {'W1': 1,'b1' :0,'W2': 2, 'b2':0, 'W3': 3,'b3':0}
for i in range(10):
    d['W{}'.format(i+1)] = i

print d

for i, v in d.iteritems():
    print i, v

{'W1': 0, 'W10': 9, 'W7': 6, 'W6': 5, 'W5': 4, 'W4': 3, 'W3': 2, 'b1': 0, 'b2': 0, 'b3': 0, 'W8': 7, 'W9': 8, 'W2': 1}
W1 0
W10 9
W7 6
W6 5
W5 4
W4 3
W3 2
b1 0
b2 0
b3 0
W8 7
W9 8
W2 1


In [10]:
# dictionary
d = {(x,x+1) : x for x in range(10)}

print d

print d[(1,2)], d[(0,1)]

{(0, 1): 0, (1, 2): 1, (6, 7): 6, (5, 6): 5, (7, 8): 7, (8, 9): 8, (4, 5): 4, (2, 3): 2, (9, 10): 9, (3, 4): 3}
1 0


In [14]:
# broadcasting
import numpy as np
a = np.array([[4,5,6],[2,9,6],[5,8,7],[1,3,3]])
print a
b =  np.random.rand(1,3)>0.2 #test with (3), (4), (1,3), (4,1)
print b
c = a + b
print c

[[4 5 6]
 [2 9 6]
 [5 8 7]
 [1 3 3]]
[[ True  True False]]
[[ 5  6  6]
 [ 3 10  6]
 [ 6  9  7]
 [ 2  4  3]]


In [2]:
import numpy as np
F = np.array([[4,5,6],[2,9,6],[5,8,7],[1,3,3]])
print F
B =  np.sum(F*F) #test with (3), (4), (1,3), (4,1)
print B
C = F*F
y=[1,2]
D=np.zeros((F.shape[0],2),dtype=np.int)
print D

print C


[[4 5 6]
 [2 9 6]
 [5 8 7]
 [1 3 3]]
355
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[16 25 36]
 [ 4 81 36]
 [25 64 49]
 [ 1  9  9]]


In [14]:
W = np.random.randn(4, 10) 
print W
X, dim=W.shape
print X, dim

[[-0.96089837 -1.00407898 -0.4083186  -0.12133459  0.24341601  0.12423645
  -0.66309739 -0.34300606  1.02494022  0.44893048]
 [ 0.576589    0.19725541 -1.2118448   0.08056687  0.82017164  1.71019467
  -1.5640457   1.03540378  0.58942501  0.5917427 ]
 [ 1.31550035  0.05095746  1.41249707  0.87262185  0.17320821 -0.11616386
   0.78489126 -0.78025295 -2.18668847  0.77416116]
 [-0.10313021 -1.33434953  0.92724456  1.39951034 -0.76825635  1.04900761
   0.60322627  0.88466864  0.33923361  1.51520711]]
4 10


In [51]:
import numpy as np
W=np.random.randn(3,5)
X=np.random.randn(10,3)
y=np.random.randn(10)
reg=0.0001  

    # Initialize the loss and gradient to zero.
loss = 0.0
dW = np.zeros_like(W)    # 得到一个和W同样shape的矩阵
dW_each = np.zeros_like(W)
num_train, dim = X.shape
num_class = W.shape[1]
f = X.dot(W)    # N by C
    # Considering the Numeric Stability
f_max = np.reshape(np.max(f, axis=1), (num_train, 1))   # 找到最大值然后减去，这样是为了防止后面的操作会出现数值上的一些偏差

pp = np.sum(np.exp(f - f_max), axis=0, keepdims=False)
print pp
#print f - f_max
a=np.random.randn(1,2)
a=W
ss=np.max(a,axis=1)
ss=ss.T
aaa=np.ones((2,3))
print ss
print a
print a.T,aaa

[ 5.08157461  2.90543197  3.75703698  3.13566837  1.20946755]
[ 1.91261909  1.54961354  1.71685485]
[[ 1.91261909 -0.99818682 -1.67944618  0.2897283   0.81937539]
 [-0.0695875  -0.66838217  1.24017242  1.54961354 -0.74098524]
 [ 1.71685485 -1.19715246  1.68425248  0.36083187 -0.53427698]]
[[ 1.91261909 -0.0695875   1.71685485]
 [-0.99818682 -0.66838217 -1.19715246]
 [-1.67944618  1.24017242  1.68425248]
 [ 0.2897283   1.54961354  0.36083187]
 [ 0.81937539 -0.74098524 -0.53427698]] [[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [49]:
scores=None
print scores

None
